version: '3.8'

name: devops-app

services:

  app:
    build:
      context: .
      args:
        - REACT_APP_API_URL=
    ports:
      - "8002:8000"
    environment:
      - PORT=8000
      - DATABASE=mongodb://mongo:27017/ecommerce
      - JWT_SECRET=demo_jwt_secret
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
